### ISSUE TITLE
Simplify CSP when all variables have the same domain

### ISSUE THREAD

**Issue by z669016** [davecom/ClassicComputerScienceProblemsInJava#2]
Hi,
You can simplify code for your samples, by adding an additional constructor which assigns the same domain to all variables.

    public CSP(List<V> variables, List<D> domain) {
         assert variables != null;
         assert domain != null;

         this.variables = variables;
         this.domains = new HashMap<>();

         for (V variable : variables) {
             domains.put(variable, domain);
             constraints.put(variable, new ArrayList<>());
         }
     }

The creation of the CSP for MapColouringConstraint will reduce to

    final CSP<String, String> csp = new CSP<>(variables, List.of("red", "green", "blue"));

**Comment by davecom** [comment]
HI @z669016,
It's a good idea. Because the book is nearing publication and I don't want to make changes for non-errors or stylistic mistakes/lack of usage of Modern Java idioms at this point, I won't do it here. But I will mark this as something to remember for the next edition or another language port.
Thank you,
David
